-- 더홍보(thehongbo.com) 초기 스키마
-- Supabase SQL Editor 에 그대로 붙여넣어 실행하거나, `supabase db push` 로 적용하세요.
-- 앱 서버는 service_role 키로 DB 에 접근하고, 공개 키(anon)로는 "공개된 글/배너/공지"만 읽을 수 있도록 RLS 를 걸어둡니다.

create extension if not exists pg_trgm;

-- ───────────── profiles ─────────────
create table if not exists public.profiles (
  id uuid primary key references auth.users (id) on delete cascade,
  nickname text not null,
  avatar_url text,
  email text,
  status text not null default 'active' check (status in ('active', 'blocked')),
  created_at timestamptz not null default now()
);

-- ───────────── posts ─────────────
create table if not exists public.posts (
  id bigint generated by default as identity primary key,
  author_id uuid references public.profiles (id) on delete set null,
  category text not null check (category in ('apps','websites','services','offline','products','content','events','free')),
  title text not null check (char_length(title) between 1 and 120),
  short_description text not null,
  description text not null,
  primary_image_url text,
  external_url text not null check (external_url ~* '^https?://'),
  platform text,
  price text,
  region text,
  address text,
  map_url text,
  tags text[] not null default '{}',
  extra jsonb not null default '{}'::jsonb,
  contact text,
  status text not null default 'active' check (status in ('active','hidden','blocked','expired','deleted')),
  admin_pinned boolean not null default false,
  curated_rank integer,
  is_seed boolean not null default false,
  view_count integer not null default 0,
  click_count integer not null default 0,
  popularity integer generated always as (view_count + click_count * 3) stored,
  search_text text not null default '',
  published_at timestamptz not null default now(),
  bumped_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  expires_at timestamptz
);

create index if not exists posts_status_bumped_idx on public.posts (status, bumped_at desc);
create index if not exists posts_category_bumped_idx on public.posts (category, status, bumped_at desc);
create index if not exists posts_region_idx on public.posts (region) where region is not null;
create index if not exists posts_author_idx on public.posts (author_id, published_at desc);
create index if not exists posts_seed_idx on public.posts (is_seed) where is_seed;
create index if not exists posts_pinned_idx on public.posts (admin_pinned, curated_rank) where admin_pinned;
create index if not exists posts_search_trgm_idx on public.posts using gin (search_text gin_trgm_ops);

-- 검색용 컬럼(제목/한 줄 소개/상세 설명/태그)을 저장 시점에 갱신
create or replace function public.posts_before_write() returns trigger
language plpgsql as $$
begin
  new.search_text := lower(
    coalesce(new.title, '') || ' ' ||
    coalesce(new.short_description, '') || ' ' ||
    coalesce(new.description, '') || ' ' ||
    coalesce(array_to_string(new.tags, ' '), '')
  );
  return new;
end;
$$;

drop trigger if exists posts_before_write on public.posts;
create trigger posts_before_write
  before insert or update on public.posts
  for each row execute function public.posts_before_write();

-- ───────────── post_images (추가 이미지, 최대 4장) ─────────────
create table if not exists public.post_images (
  id bigint generated by default as identity primary key,
  post_id bigint not null references public.posts (id) on delete cascade,
  image_url text not null,
  sort_order integer not null default 0
);
create index if not exists post_images_post_idx on public.post_images (post_id, sort_order);

-- ───────────── reports ─────────────
create table if not exists public.reports (
  id bigint generated by default as identity primary key,
  post_id bigint not null references public.posts (id) on delete cascade,
  reporter_id uuid references public.profiles (id) on delete set null,
  reporter_anon text,
  reason text not null,
  detail text,
  status text not null default 'open' check (status in ('open', 'resolved', 'rejected')),
  created_at timestamptz not null default now()
);
create index if not exists reports_status_idx on public.reports (status, created_at desc);
create index if not exists reports_post_idx on public.reports (post_id);

-- ───────────── banners / notices ─────────────
create table if not exists public.banners (
  id bigint generated by default as identity primary key,
  title text not null,
  subtitle text,
  image_url text,
  target_url text not null,
  placement text not null default 'side' check (placement in ('side', 'strip')),
  theme text not null default 'coral' check (theme in ('coral', 'blue', 'mint', 'violet', 'amber')),
  sort_order integer not null default 0,
  is_active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.notices (
  id bigint generated by default as identity primary key,
  title text not null,
  body text not null default '',
  is_pinned boolean not null default false,
  published_at timestamptz not null default now()
);

-- ───────────── analytics_events (가볍게 시작) ─────────────
create table if not exists public.analytics_events (
  id bigint generated by default as identity primary key,
  event_type text not null,
  post_id bigint references public.posts (id) on delete cascade,
  anonymous_id text,
  user_id uuid,
  created_at timestamptz not null default now()
);
create index if not exists events_created_idx on public.analytics_events (created_at desc);
create index if not exists events_post_idx on public.analytics_events (post_id, created_at desc);
create index if not exists events_dedupe_idx on public.analytics_events (event_type, post_id, anonymous_id, created_at desc);

-- ───────────── 함수 ─────────────
create or replace function public.bump_post_counter(p_post_id bigint, p_kind text) returns void
language sql security definer set search_path = public as $$
  update public.posts
     set view_count  = view_count  + (case when p_kind = 'view'  then 1 else 0 end),
         click_count = click_count + (case when p_kind = 'click' then 1 else 0 end)
   where id = p_post_id;
$$;

create or replace function public.popular_scores(p_hours integer, p_limit integer)
returns table (post_id bigint, score bigint)
language sql security definer set search_path = public as $$
  select e.post_id,
         sum(case e.event_type when 'post_view' then 1 when 'external_click' then 3 else 0 end)::bigint as score
    from public.analytics_events e
    join public.posts p on p.id = e.post_id
   where e.created_at > now() - make_interval(hours => p_hours)
     and e.post_id is not null
     and p.status = 'active'
   group by e.post_id
  having sum(case e.event_type when 'post_view' then 1 when 'external_click' then 3 else 0 end) > 0
   order by score desc
   limit p_limit;
$$;

revoke all on function public.bump_post_counter(bigint, text) from public, anon, authenticated;
revoke all on function public.popular_scores(integer, integer) from public, anon, authenticated;
grant execute on function public.bump_post_counter(bigint, text) to service_role;
grant execute on function public.popular_scores(integer, integer) to service_role;

-- ───────────── RLS ─────────────
-- 서버(service_role)는 RLS 를 우회합니다. 공개 키(anon)로는 공개 데이터만 읽을 수 있습니다.
alter table public.profiles enable row level security;
alter table public.posts enable row level security;
alter table public.post_images enable row level security;
alter table public.reports enable row level security;
alter table public.banners enable row level security;
alter table public.notices enable row level security;
alter table public.analytics_events enable row level security;

drop policy if exists "profiles read own" on public.profiles;
create policy "profiles read own" on public.profiles for select to authenticated using (auth.uid() = id);

drop policy if exists "posts public read" on public.posts;
create policy "posts public read" on public.posts for select to anon, authenticated
  using (status = 'active' and (expires_at is null or expires_at > now()));

drop policy if exists "post_images public read" on public.post_images;
create policy "post_images public read" on public.post_images for select to anon, authenticated
  using (exists (select 1 from public.posts p where p.id = post_id and p.status = 'active'));

drop policy if exists "banners public read" on public.banners;
create policy "banners public read" on public.banners for select to anon, authenticated using (is_active);

drop policy if exists "notices public read" on public.notices;
create policy "notices public read" on public.notices for select to anon, authenticated using (true);

-- reports / analytics_events 는 정책이 없으므로 service_role 외에는 접근할 수 없습니다.

-- ───────────── Storage: 홍보 이미지 ─────────────
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('post-images', 'post-images', true, 4194304, array['image/webp', 'image/jpeg', 'image/png', 'image/gif'])
on conflict (id) do update
  set public = excluded.public,
      file_size_limit = excluded.file_size_limit,
      allowed_mime_types = excluded.allowed_mime_types;
-- 업로드는 서버(service_role)의 /api/upload 를 통해서만 이루어지므로 업로드용 storage 정책은 만들지 않습니다.
